language: c
sudo: required # we get a VM + SUDO
dist: xenial # latest

# install dependencies
before_install:
    # install dependecies for sac2c
    - sudo apt-get update -qq
    - sudo apt-get install -qq uuid-dev uuid-runtime
    # sanity check that cmake is the right version (should be 3.12)
    - cmake --version
    # install sac2c (always latest release)
    - travis_retry wget --no-check-certificate --quiet -O sac2c.deb http://www.sac-home.org/packages/weekly/Ubl16/1.3.3-359-1/basic/sac2c-1.3.3-MijasCosta-359-g856d44-omnibus.deb
    - sudo dpkg --force-all -i sac2c.deb
    - sac2c -V

before_script:
    - mkdir build
    - mkdir ${HOME}/.sac2crc

script:
    - cd build
    # to save time we only build one target and increase the number of files we generate
    - cmake -DTARGETS=mt_pth -DLINKSETSIZE=250 ..
    # we need to test that make actually completed:
    - make -j3 2>&1 | tee build.log; travis_assert ${PIPESTATUS[0]}
    - if [ $(grep -i 'warning' build.log | wc -l) -gt 0 ]; then
        echo "+++ ${WARN_NUM} warnings detected +++";
        grep -i 'warning' build.log;
        travis_terminate 1;
      fi
