language: c
sudo: required
dist: trusty # latest

# install dependencies
before_install:
    # install dependecies for sac2c
    - sudo apt-get update -qq
    - sudo apt-get install -qq libhwloc-dev uuid-dev uuid-runtime
    # install cmake
    - CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.tar.gz"
    - mkdir cmake-latest
    - travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake-latest
    - export PATH=${TRAVIS_BUILD_DIR}/cmake-latest/bin:${PATH}
    - cmake --version
    # install sac2c
    - travis_retry wget --no-check-certificate --quiet http://www.sac-home.org/packages/DEB/1.2-beta/Deb7/sac2c-1.2-beta-BlackForest-467-gce8d4-omnibus.deb
    - sudo dpkg -i sac2c-1.2-beta-BlackForest-467-gce8d4-omnibus.deb

before_script:
    - mkdir build
    - mkdir ${HOME}/.sac2crc

script:
    - cd build
    - cmake -DTARGETS=mt_pth ..
    - make -j3
