name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Get HEAD and submodules
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Install sac2c-basic
        run: |
          wget https://gitlab.science.ru.nl/sac-group/sac-packages/-/raw/master/packages/weekly/Ubl18/1.3.3-383-1/basic/sac2c-1.3.3-MijasCosta-383-g6ea12-omnibus.deb
          sudo dpkg -i sac2c-1.3.3-MijasCosta-383-g6ea12-omnibus.deb
      - name: Create build dir
        run: |
          cmake -E make_directory ${{runner.workspace}}/build
          mkdir $HOME/.sac2crc
      - name: Configure build-system
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake -DLINKSETSIZE=200 -DFULLTYPES=ON $GITHUB_WORKSPACE
      - name: Build
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . -j 2

